version: "3.4"
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - backend

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10002:10002"
    volumes:
      - ./azurite/data:/data
    command: azurite-table --tableHost 0.0.0.0 --tablePort 10002 --location /data
    networks:
      - backend

  data_processor:
    build:
      context: ./
      dockerfile: Docker/Dockerfile_data_processor
    image: data_processor
    restart: always
    env_file:
      - config/env/data_processor.env
    volumes:
      - ./data:/data
    depends_on:
      - mosquitto
      - azurite
    networks:
      - backend

  data_analyzer:
    build:
      context: ./
      dockerfile: Docker/Dockerfile_data_analyzer
    image: data_analyzer
    ports:
      - "8501:8501"
    env_file:
      - config/env/data_analyzer.env
    depends_on:
      - mosquitto
      - azurite
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24