FROM python:3.9.4-slim
RUN apt update -y
RUN apt install -y libopencv-dev
RUN apt install -y libgl1-mesa-dev

COPY ./requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt

WORKDIR /opt/data_analyzer
COPY src/ /opt/data_analyzer

ENV PYTHONPATH=${PYTHONPATH}:.
CMD ["streamlit", "run", "data_analyzer.py"]
