FROM python:3.9.4-slim
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y libssl-dev

COPY ./requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt

WORKDIR /opt/data_processor
COPY src/ /opt/data_processor
RUN mkdir log
RUN mkdir data

ENV PYTHONPATH=${PYTHONPATH}:.
CMD ["python", "data_processor.py"]
